//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrinhoUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrinhoUsuario()
        {
            this.CarrinhoUsuarioProdutoes = new HashSet<CarrinhoUsuarioProduto>();
        }
    
        public int IdCarrinhoUsuario { get; set; }
        public decimal QuantidadeProdutos { get; set; }
        public decimal PrecoTotal { get; set; }
        public int Carrinho_IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrinhoUsuarioProduto> CarrinhoUsuarioProdutoes { get; set; }
    }
}
