//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.CarrinhoUsuarios = new HashSet<CarrinhoUsuario>();
        }
    
        public int CodigoProduto { get; set; }
        public string NomeProduto { get; set; }
        public decimal PesoVolumeProduto { get; set; }
        public decimal PrecoProduto { get; set; }
        public decimal EstoqueProduto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrinhoUsuario> CarrinhoUsuarios { get; set; }
    }
}
