//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutoItem()
        {
            this.CarrinhoUsuarioProdutoes = new HashSet<CarrinhoUsuarioProduto>();
        }
    
        public int CodigoProdutoItem { get; set; }
        public int CodigoProduto { get; set; }
        public string SituacaoItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrinhoUsuarioProduto> CarrinhoUsuarioProdutoes { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
